version: '3.3'
services:
  landing:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
    restart: always
    ports:
      - 80:80
    command: /bin/bash -c "nginx -g 'daemon off;'"